version: build{build}

branches:
  except:
    - project/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - C:\Qt\5.9.4\msvc2017_64\bin\qmake.exe TableEdit.pro
  - nmake & exit 0
